# Generated by Django 4.2 on 2025-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentinemessage',
            name='generated_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='recipient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='relationship',
            field=models.CharField(choices=[('friend', 'Friend'), ('partner', 'Partner'), ('family', 'Family')], max_length=20),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='sender_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
