# Generated by Django 4.2 on 2025-01-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_alter_valentinemessage_generated_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentinemessage',
            name='relationship',
            field=models.CharField(choices=[('girlfriend', 'Girlfriend'), ('boyfriend', 'Boyfriend'), ('spouse', 'Spouse'), ('crush', 'Crush'), ('friend', 'Friend')], max_length=20),
        ),
    ]
