# Generated by Django 4.2 on 2025-01-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_alter_valentinemessage_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valentinemessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='valentinemessage',
            name='phone_country',
            field=models.CharField(default='KE', help_text='ISO 3166-1 alpha-2 country code (e.g., KE, US, GB)', max_length=2),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the message was created'),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='description',
            field=models.TextField(help_text='What you love about the recipient'),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='email',
            field=models.EmailField(help_text='Email address where the message will be sent', max_length=254),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='generated_message',
            field=models.TextField(blank=True, help_text="AI-generated Valentine's message", null=True),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +254XXXXXXXXX)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='recipient_name',
            field=models.CharField(help_text='Name of the person receiving the message', max_length=255),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='relationship',
            field=models.CharField(choices=[('girlfriend', 'Girlfriend'), ('boyfriend', 'Boyfriend'), ('spouse', 'Spouse'), ('crush', 'Crush'), ('friend', 'Friend')], help_text='Relationship with the recipient', max_length=20),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='scheduled_for',
            field=models.DateTimeField(help_text='When the message should be sent'),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='sender_name',
            field=models.CharField(help_text='Name of the person sending the message', max_length=255),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Current status of the message', max_length=10),
        ),
        migrations.AddIndex(
            model_name='valentinemessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='messages_ap_status_991870_idx'),
        ),
        migrations.AddIndex(
            model_name='valentinemessage',
            index=models.Index(fields=['created_at'], name='messages_ap_created_504745_idx'),
        ),
    ]
