# Generated by Django 4.2 on 2025-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_alter_valentinemessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valentinemessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Current status of the message', max_length=10),
        ),
    ]
