# Generated by Django 4.2 on 2025-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0005_alter_valentinemessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='valentinemessage',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email Only'), ('sms', 'SMS Only'), ('whatsapp', 'WhatsApp Only'), ('email_sms', 'Email and SMS'), ('email_whatsapp', 'Email and WhatsApp')], default='email', help_text='How the message should be delivered', max_length=20),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address where the message will be sent', max_length=254, null=True),
        ),
    ]
