# Generated by Django 4.2 on 2025-01-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0006_valentinemessage_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valentinemessage',
            name='error_details',
            field=models.JSONField(blank=True, help_text='Detailed error information if sending failed', null=True),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email Only'), ('whatsapp', 'WhatsApp Only'), ('email_whatsapp', 'Email and WhatsApp')], default='whatsapp', help_text='How the message should be delivered', max_length=20),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number in international format (e.g., +254XXXXXXXXX)', max_length=20, null=True),
        ),
    ]
