# Generated by Django 4.2 on 2025-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0007_valentinemessage_error_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_description', models.TextField(help_text='Description of the special service requested')),
                ('contact_number', models.CharField(help_text='Contact number of the requester', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', help_text='Current status of the premium service request', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='valentinemessage',
            name='custom_message',
            field=models.TextField(blank=True, help_text='Custom written message', null=True),
        ),
        migrations.AddField(
            model_name='valentinemessage',
            name='message_type',
            field=models.CharField(choices=[('generated', 'AI Generated'), ('custom', 'Custom Written')], default='generated', help_text='Type of message (AI generated or custom written)', max_length=10),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='description',
            field=models.TextField(blank=True, help_text='What you love about the recipient (for generated messages)', null=True),
        ),
        migrations.AlterField(
            model_name='valentinemessage',
            name='relationship',
            field=models.CharField(choices=[('girlfriend', 'Girlfriend'), ('boyfriend', 'Boyfriend'), ('spouse', 'Spouse'), ('crush', 'Crush'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('boss', 'Boss'), ('friend_with_benefits', 'Friend With Benefits')], help_text='Relationship with the recipient', max_length=20),
        ),
        migrations.AddIndex(
            model_name='premiumservicerequest',
            index=models.Index(fields=['status'], name='messages_ap_status_921881_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumservicerequest',
            index=models.Index(fields=['created_at'], name='messages_ap_created_f27e77_idx'),
        ),
    ]
